-- Script para adicionar e atualizar os departamentos (setores) dos funcionários
-- Execute este script no SQL Editor do Supabase.

-- 1. Adicionar a coluna department se ela não existir
ALTER TABLE public.people ADD COLUMN IF NOT EXISTS department TEXT;

-- 2. Atualizar os departamentos (Setores) em massa
UPDATE public.people AS p
SET department = v.dept
FROM (VALUES
    ('Adam de Pierre Pavan', '3D'),
    ('Ademilson Souza de Jesus', 'ACABAMENTO'),
    ('Adilson Felix de Oliveira', 'MARCENARIA'),
    ('Adolfo Belchior de Sousa', 'MARCENARIA'),
    ('Adriano Mariano', 'SERRALHERIA'),
    ('Adson Silva Costa', 'ACABAMENTO'),
    ('Aecio Vieira Zimerer', 'LAMINAÇÃO'),
    ('Agenilson Bernardo da Silva', 'SERRALHERIA'),
    ('Agenor Silva de Almeida', 'SERRALHERIA'),
    ('Airton Souza de Jesus', 'MARCENARIA'),
    ('Alan Lima dos Anjos', 'ESCULTURA'),
    ('Alan Soares Machado', 'PINTURA'),
    ('Alecsandro de Paula dos Anjos', 'MARCENARIA'),
    ('Alex Jesus Gomes', 'ACABAMENTO'),
    ('Alex Martiliano da Silva', 'EQUIPE FELIPE'),
    ('Alexandre Augusto Lacerda', 'ADMINISTRATIVO'),
    ('Alexandre Augusto Teixeira', 'PRODUÇÃO'),
    ('Alexandre Batista Freitas da Silva', 'ESCULTURA'),
    ('Alexandre da Silva', 'SERRALHERIA'),
    ('Alexandre Pereira de Lima', 'GERAL'),
    ('Alexrandre Porfirio dos Santos', 'MARCENARIA'),
    ('Alexandre Ricardo dos Santos', 'PINTURA'),
    ('Alexandro Antunes de Sousa', 'MARCENARIA'),
    ('Aline Brito Levi da Silva', 'ESCULTURA'),
    ('Allan Bruno Ribeiro de Lima', 'SERRALHERIA'),
    ('Ana Paula de Jesus Santos', 'ESCULTURA'),
    ('Ana Rogeria da Silva', 'ESCULTURA'),
    ('Ana Sabrina dos Santos Xavier', 'ESCULTURA'),
    ('Anderson de Jesus Silva', 'PINTURA'),
    ('Anderson Gomes Nunes', 'ACABAMENTO'),
    ('Anderson Pinheiro de Sá', 'ACABAMENTO'),
    ('Anderson Ramos Cardoso', 'EQUIPE FELIPE'),
    ('Anderson Viana Medeiros', 'SERRALHERIA'),
    ('Andre dos Reis Santos', 'ADMINISTRATIVO'),
    ('André Duarte dos Santos', 'MARCENARIA'),
    ('Andreia Franco', 'ESCULTURA'),
    ('Andrey Buscarani dos Santos Silva', 'ESCULTURA'),
    ('Angelica Ferreira Magalhães', 'ESCULTURA'),
    ('Anny Vitoria da Silva Rodrigues', 'ESCULTURA'),
    ('Antonio Calixto de Sousa', 'LAMINAÇÃO'),
    ('Antonio Carlos Bezerra dos Santos', 'MARCENARIA'),
    ('Antonio Felipe Alves Ramos', 'DESMONTAGEM FORTALEZA'),
    ('Antonio Francisco Gomes de Oliveira', 'MARCENARIA'),
    ('Antonio Marcos do Nascimento', 'MARCENARIA'),
    ('Antonio Paulo Teixeira', 'ACABAMENTO'),
    ('Antonio Rivaldo Gomes Bezerra', 'ELETRICA'),
    ('Antonio Roberto Santos de Oliveira', 'MARCENARIA'),
    ('Ashiley Ney Pereira Ribeiro de Oliveira', 'SERRALHERIA'),
    ('Beatriz Cezar Valerio de Jesus', 'ADMINISTRATIVO'),
    ('Brenno Mendes de Sousa', 'ROUTER'),
    ('Bruno Almeida da Silva', 'EQUIPE LUIZ'),
    ('Bruno Alves de Moraes Sarmento Duarte', 'ADMINISTRATIVO'),
    ('Bruno de Lima Silva', 'PINTURA'),
    ('Bruno Inacio Alves Silva', 'SERRALHERIA'),
    ('Bruno Leandro França Marvino', 'GERAL'),
    ('Bruno Luiz de Souza Franzin', 'SERRALHERIA'),
    ('Bruno Vilas Boas de Oliveira', 'SERRALHERIA'),
    ('Bruno Yoshiharu Sakosigue Correa', '3D'),
    ('Carla Chimera Nardim', 'ADMINISTRATIVO'),
    ('Carlos Alberto Silva Ramilo', 'ACABAMENTO'),
    ('Carlos Alberto Beserra Goes', 'ESCULTURA'),
    ('Carlos Alberto da Silva', 'ALMOXARIFADO'),
    ('Carlos Eduardo Pereira Silva', 'ACABAMENTO'),
    ('Carlos Farias dos Santos', 'SERRALHERIA'),
    ('Carlos Henrique Dias da Cruz', 'MARCENARIA'),
    ('Carlos Alberto dos Santos Junior', 'SERRALHERIA'),
    ('Carlos Rafael Dias da Cruz', 'MARCENARIA'),
    ('Cassiano Cabral da Silva', 'MARCENARIA'),
    ('Cassio Breno Faustino do Nascimento', 'SERRALHERIA'),
    ('Cicero Bezerra da Cunha', 'DESMONTAGEM FORTALEZA'),
    ('Cicero Manoel da Silva', 'GERAL'),
    ('João Cicero Martins da Silva', 'MARCENARIA'),
    ('Cicero Romão Santos de Souza', 'ESCULTURA'),
    ('Cintia Priscila dos Santos', 'PINTURA'),
    ('Claudinei Cherchiglia', 'SERRALHERIA'),
    ('Claudio Roberto da Silva', 'SERRALHERIA'),
    ('Clayton de Paula dos Anjos', 'MARCENARIA'),
    ('Cleber de Melo Simões', 'ADMINISTRATIVO'),
    ('Cleiton Cavasso de lima', 'PINTURA'),
    ('Cleiton do Carmo de Novais', 'SERRALHERIA'),
    ('Cristiano Chiarella Ortiz', 'ADMINISTRATIVO'),
    ('Cristiano de Albuquerque', 'ACABAMENTO'),
    ('Cristiano de Jesus Ferreira', 'MARCENARIA'),
    ('Cristiano de Oliveira', 'PINTURA'),
    ('Cristiano Francisco de Oliveira', 'ELETRICA'),
    ('Cristiano Oliveira', 'SERRALHERIA'),
    ('Cristiano Trujilho', 'PINTURA'),
    ('Daniel Bartolo Felix', 'LAMINAÇÃO'),
    ('Daniel da Silva Bezerra', 'LAMINAÇÃO'),
    ('Daniel Matias da Costa', 'MARCENARIA'),
    ('Daniela Maria Teixeira', 'MARCENARIA'),
    ('Danilo dos Santos Mattos', 'SERRALHERIA'),
    ('Danilo Santos Poloni', 'MARCENARIA'),
    ('Dannilo Richerdson C Queiroz', 'GERAL'),
    ('Davi Aragão Andrade Pereira', 'ESCULTURA'),
    ('Davi Magistrali Rocco', '3D'),
    ('Davi Oliveira de Souza', 'MARCENARIA'),
    ('David Ferreira Alves', 'LAMINAÇÃO'),
    ('Debora dos Santos Aragao', 'ESCULTURA'),
    ('Debora Vitoria Oliveira Bezerra', 'ESCULTURA'),
    ('Deborah Aragao Verissimo Ramalho', 'ESCULTURA'),
    ('Denesio Cardoso', 'ALMOXARIFADO'),
    ('Denis Aparecido Rosa Santana', 'MARCENARIA'),
    ('Denis Danilo da Silva Bezerra', 'LAMINAÇÃO'),
    ('Denis Araujo Justos', 'MARCENARIA'),
    ('Denison de Freitas Francisco Sales', 'PINTURA'),
    ('Dennis de Oliveira Farkas', 'MARCENARIA'),
    ('Deyvson Gomes da Silva', 'PINTURA'),
    ('Diego da Conceição', 'SERRALHERIA'),
    ('Diego Evandro Maria Martins', '3D'),
    ('Diego Ferreira Lopes', 'ESCULTURA'),
    ('Diego Moreira Dias', 'MARCENARIA'),
    ('Diemerson Jesus da Conceição', 'MARCENARIA'),
    ('Diogo da Cuz Batista', 'PINTURA'),
    ('Donald Pereira Rodrigues', 'MARCENARIA'),
    ('Donizete Luiz dos Santos', 'MARCENARIA'),
    ('Douglas da Silva', 'MONTAGEM RJ'),
    ('Douglas de Moraes', 'MARCENARIA'),
    ('Edersom Mendes dos Santos', 'SERRALHERIA'),
    ('Edigenaldo Leal da Costa', 'ACABAMENTO'),
    ('Edilson Coelho Ferreria', 'PINTURA'),
    ('Edilson Jose de Arruda', 'ACABAMENTO'),
    ('Edmilson Jose da Silva', 'PINTURA'),
    ('Edinaldo da Silva', 'EQUIPE LUIZ'),
    ('Edmar Nunes Bento', 'MARCENARIA'),
    ('Edmilson de Queiroz Brandão', 'ACABAMENTO'),
    ('Edson Viana Homena', 'MARCENARIA'),
    ('Eduardo Araujo Mesquita', 'ROUTER'),
    ('Eduardo Cardoso Garcia', 'PINTURA'),
    ('Eduardo Melillo', 'EQUIPE LUIZ'),
    ('Eduardo Rodrigues Ferraz', 'ESCULTURA'),
    ('Eduardo Tadeu Amador', 'PINTURA'),
    ('Edvaldo Gomes da Silva', 'MARCENARIA'),
    ('Edvan Gonçalves Dantas', 'SERRALHERIA'),
    ('Edwin de Carvalho Pereira', 'DADOS'),
    ('Elias dos Santos Aragao', 'GERAL'),
    ('Eliezer Silva Santos Oliveira', 'SERRALHERIA'),
    ('Eloisio Marques de Oliveira', 'EQUIPE LUIZ'),
    ('Elton Luis Salles de Carvalho', 'PINTURA'),
    ('Emerson Nunes de Santana', 'MARCENARIA'),
    ('Emilena dos Santos Aragão', 'ESCULTURA'),
    ('Erick Pereira Santana', 'PINTURA'),
    ('Erivaldo Lopes Oliveira', 'SERRALHERIA'),
    ('Esteffani Xavier Nunes', 'ESCULTURA'),
    ('Estevão Martiliano da Silva', 'MARCENARIA'),
    ('Eugenio Paulino Oliveira de Barros', 'ACABAMENTO'),
    ('Evaldo Correia da Silva', 'ELETRICA'),
    ('Evandro Luiz de Moraes', 'LAMINAÇÃO'),
    ('Evelyn Cristiny Reis da Silva', 'COMPRAS'),
    ('Everton Lima Tavares', 'EQUIPE FELIPE'),
    ('Everton Simões Fernandes Teixeira', 'ADMINISTRATIVO'),
    ('Fabiano Moreira Santos', 'ELETRICA'),
    ('Fabio Candido da Silva', 'MARCENARIA'),
    ('Fabio Miguel dos Santos', 'SERRALHERIA'),
    ('Fabio Rogerio Marques', 'PINTURA'),
    ('Fabio Sinisgalli Machado', 'PINTURA'),
    ('Fabricio Aparecido Fernandes dos Santos', 'ESCULTURA'),
    ('Fabricio Saraiva Duarte', 'ADMINISTRATIVO'),
    ('Felipe Araujo Ramilo', 'LAMINAÇÃO'),
    ('Felipe Augusto da Silva', 'MARCENARIA'),
    ('Felipe Marques Fedelis de Souza', 'ESCULTURA'),
    ('Felipe Soares Leonel', 'ESCULTURA'),
    ('Felipe de Souza Vieira', 'PINTURA'),
    ('Felipe Wesley de Santana', 'MARCENARIA'),
    ('Felipe Weygner Lopes da Silva', 'DESMONTAGEM FORTALEZA'),
    ('Fernanda Silva Azevedo', 'SERRALHERIA'),
    ('Fernando da Costa Martins', 'MARCENARIA'),
    ('Fernando dos Santos Soldi', 'MARCENARIA'),
    ('Fernando Gonçalves de Melo Filho', 'GERAL'),
    ('Flavio Dias de Andrade', 'MARCENARIA'),
    ('Flavio Freire de Queiroz Costa', 'MARCENARIA'),
    ('Franciluvio Gomes da Silva', 'LAMINAÇÃO'),
    ('Francisco Cleio Gomes de Souza', 'MARCENARIA'),
    ('Francisco Helio da Silva Gomes', 'MARCENARIA'),
    ('Francisco Jose Gomes Mendes', 'ACABAMENTO'),
    ('Francisco Luan Fernandes Duarte', 'ESCULTURA'),
    ('Francisco Ronaldo Vericio Junior', 'ACABAMENTO'),
    ('Francisco Segundo de Oliveira Mariz', 'ELETRICA'),
    ('Gabriel Augusto Nunes', 'ESCULTURA'),
    ('Gabriel Barros Lima', 'DESMONTAGEM FORTALEZA'),
    ('Gabriel Bispo', 'ESCULTURA'),
    ('Gabriel Costa da Silva', 'SERRALHERIA'),
    ('Gabriel Dias da Silva', 'LAMINAÇÃO'),
    ('Gabriel Franco de Souza', 'ESCULTURA'),
    ('Gabriel Marques Vieira', 'Almoxarifado'),
    ('Gabriel Vieira Souza Santos', 'ESCULTURA'),
    ('Gabriela Alves da Silva', 'ESCULTURA'),
    ('Gabriela Aragão Ferreira', 'COMERCIAL'),
    ('Gabrielle Aparecida Ferreira Tomaz', 'ESCULTURA'),
    ('Genilson do Carmo de Novais', 'SERRALHERIA'),
    ('Geovane José da Silva', 'SERRALHERIA'),
    ('Geovanna Luiza Silva Chagas', 'ESCULTURA'),
    ('Gerson Ricardo de Souza Oliveira Alves', 'SERRALHERIA'),
    ('Glayson Alves Souza', 'MARCENARIA'),
    ('Gleison Barreto da Fonseca', 'SERRALHERIA'),
    ('Guilherme Florencio Lisboa', 'COMERCIAL'),
    ('Gustavo de oliveira', 'MARCENARIA'),
    ('Gustavo Felipe de Oliveira', 'ESCULTURA'),
    ('Gustavo Inacio Pares', 'ESCULTURA'),
    ('Gustavo Santos Policarpo Silva', 'LAMINAÇÃO'),
    ('Gustavo Silva Soares', 'ESCULTURA'),
    ('Gustavo Yan da Rocha Almeida', 'ESCULTURA'),
    ('Hector Gabriel Milano Hernandes', 'MARCENARIA'),
    ('Heitor Paduam', 'SERRALHERIA'),
    ('Helvecio da Silva', 'MARCENARIA'),
    ('Henrique Barbosa Alves', 'ESCULTURA'),
    ('Herick Araujo de Souza', 'SERRALHERIA'),
    ('Humberto Biagi Mminer', 'PINTURA'),
    ('Humberto Henrique Ferreira Bueno da Silva', 'MARCENARIA'),
    ('Iago Amaral', 'EQUIPE FELIPE'),
    ('Iago Kauan Bernegosso', 'MARCENARIA'),
    ('Igor e Silva dos Santos', 'PINTURA'),
    ('Igor Matheus Nunes de Almeida', 'MARCENARIA'),
    ('Ingrid Bezerra Mendes e Silva', 'ESCULTURA'),
    ('Isaquiel Santos de Lima', 'MARCENARIA'),
    ('Ismael Barbosa da Silva', 'MARCENARIA'),
    ('Italo Elmer Lima', 'ESCULTURA'),
    ('Italo Guitar de Santana dos Santos', 'LAMINAÇÃO'),
    ('Jackson Jose da Silva', 'MARCENARIA'),
    ('Jackson Muller dos Santos', 'MARCENARIA'),
    ('Jailson Alonso de Souza', 'ELETRICA'),
    ('Janaina Santos Silva', 'ESCULTURA'),
    ('Janivaldo Roberto de Luna', 'LAMINAÇÃO'),
    ('Jaqueline Kilma Silva Lins', 'ESCULTURA'),
    ('Jaquison Limeira Santos', 'MARCENARIA'),
    ('Jasiel da Silva Bezerra', 'SERRALHERIA'),
    ('Jean Carlo Honorio da Silva Junior', 'MARCENARIA'),
    ('Jefferson dos Santos Barbosa', 'SERRALHERIA'),
    ('Jefferson Gomes dos Santos', 'MARCENARIA'),
    ('Jessica de Souza Franco', 'ADMINISTRATIVO'),
    ('Jesualdo Pereira da Lima Teles', 'LAMINAÇÃO'),
    ('Jesus Sebastian', 'SERRALHERIA'),
    ('Jhonatan Carlos Candido', 'MARCENARIA'),
    ('Jhonatas Rocha Bernardes da Silva', 'ESCULTURA'),
    ('Jhonathan Italo Fernandes Veide', 'SERRALHERIA'),
    ('João Carlos Pinheiro', 'SERRALHERIA'),
    ('João Carlos Silva de Araujo', 'SERRALHERIA'),
    ('João Cícero Martins da Silva', 'MARCENARIA'),
    ('Joao Gabriel Pereira Barbosa', 'SERRALHERIA'),
    ('Joao Luiz Madureira', 'LAMINAÇÃO'),
    ('Joao Victor Mendes de Sousa', 'ESCULTURA'),
    ('João Vitor Duarte de Sousa', 'MARCENARIA'),
    ('Jobanny Jose Urbano Aleman', 'SERRALHERIA'),
    ('Joel Neves da Conceicao Filho', 'TAPECARIA'),
    ('John Diego Benites da Silva', 'SERRALHERIA'),
    ('Johny Cesar de Brito Tavares', 'MARCENARIA'),
    ('Jonata Arrais do Nascimento', 'ESCULTURA'),
    ('Jonata de Sousa Alexandre', 'SERRALHERIA'),
    ('Jose Augusto Silva Ferreira', 'MARCENARIA'),
    ('Jose Carlos Cavalcante', 'LAMINAÇÃO'),
    ('Jose Correia de Aarujo Neto', 'ESCULTURA'),
    ('Jose da Silva Araujo', 'MARCENARIA'),
    ('Jose dos Santos Xavier', 'ACABAMENTO'),
    ('Jose Edson Paduan', 'SERRALHERIA'),
    ('Jose Everton de Jesus', 'MARCENARIA'),
    ('Jose Francisco Barros da Silva', 'MARCENARIA'),
    ('José Gabriel Reis Rodrigues', 'PINTURA'),
    ('Jose Ilton da Silva Santos', 'SERRALHERIA'),
    ('Jose Jonas Carvalho Silva', 'ACABAMENTO'),
    ('Jose Luiz Marin', 'ADMINISTRATIVO'),
    ('Jose Patricio Calixto dos Santos', 'SERRALHERIA'),
    ('jose Raimundo dos Santos Ferreira', 'ACABAMENTO'),
    ('Joseph Pereira Bultcher', 'ACABAMENTO'),
    ('Josilene Sousa de Araujo', 'ESCULTURA'),
    ('Josimar Ferreira de Franca', 'EQUIPE LUIZ'),
    ('Josimar Santos Marambaia', 'MARCENARIA'),
    ('Josinaldo Gonzaga de Melo', 'SERRALHERIA'),
    ('Jozilda Nunes de Oliveira', 'COMPRAS'),
    ('Julia de Paula Ferreira', 'COMPRAS'),
    ('Juliane Silva dos Anjos', 'COMERCIAL'),
    ('Julio Cesar Soares de Souza', 'SERRALHERIA'),
    ('Julio Cesar Pinheiro Carneiro', 'GERAL'),
    ('Kairon Aguiar da Silva', 'ESCULTURA'),
    ('Karine Alves Silva', 'ESCULTURA'),
    ('Kauan Ribeiro da Silva', 'EQUIPE FELIPE'),
    ('Keisy Minene Pereira Marques Baciga', 'ADMINISTRATIVO'),
    ('Laercio Jose de Souza', 'MARCENARIA'),
    ('Larissa Rodrigues Costa Araujo', 'ESCULTURA'),
    ('Leandro Alves', 'PINTURA'),
    ('Leandro Aparecido dos Anjos', 'MARCENARIA'),
    ('Leandro Coelho', 'SERRALHERIA'),
    ('Leandro Oliveira Ferreira', 'PINTURA'),
    ('Leandro Pereira', 'PINTURA'),
    ('Leandro Rodrigues de Morais', 'PINTURA'),
    ('Leonardo da SIlva Pereira', 'ESCULTURA'),
    ('Marcos Fernandes', 'SERRALHERIA'),
    ('Leonardo Frank Devis Avila', 'SERRALHERIA'),
    ('Leonardo Guilherme de Souza', '3D'),
    ('Leonardo Roberto Pereira da Silva', 'GERAL'),
    ('Leticia Oliveira da Silva', 'ADMINISTRATIVO'),
    ('Leudimar Maria Costa Andrade', 'RH'),
    ('Luan Leonardo dos Santos', 'EQUIPE FELIPE'),
    ('Luana Aparecida de Almeida Silva', 'ESCULTURA'),
    ('Luana de Jesus dos Santos', 'ESCULTURA'),
    ('Lucas Almeida', 'SERRALHERIA'),
    ('Lucas Alves Pereira Costa', 'MARCENARIA'),
    ('Lucas Caetano dos Santos e Silva', 'ESCULTURA'),
    ('Lucas Eduardo de Araujo', 'ACABAMENTO'),
    ('Lucas de Oliveira Messias', 'MARCENARIA'),
    ('Lucas Santos de Araujo', 'ESCULTURA'),
    ('Luciano Andrioni da Costa', 'MARCENARIA'),
    ('Luciano Firmino da Silva', 'SERRALHERIA'),
    ('Luciano Silva dos Santos', 'GERAL'),
    ('Luciene da Silva Santos', 'LIMPEZA'),
    ('Luis Antonio Guimaraes', 'EQUIPE LUIZ'),
    ('Luis Fernando Batista Soares', 'ESCULTURA'),
    ('Luiz Antonio Guimarães de Almenida', 'SERRALHERIA'),
    ('Luiz Eduardo Bezerra Silva', 'ESCULTURA'),
    ('Luiz Felipe Silva Francisco', 'SERRALHERIA'),
    ('Luiz Felipe da Silva', 'MARCENARIA'),
    ('Luiz Fernando de Oliveira', 'PINTURA'),
    ('Luiz Fernando Paduan de Lima', 'SERRALHERIA'),
    ('Luiz Gustavo dos Santos de Oliveira', 'ESCULTURA'),
    ('Luiz Gustavo do Rosario de Almeida Vaz', 'PRODUÇÃO'),
    ('Luiz Gustavo Silva', 'PINTURA'),
    ('Luiz Henrique de Jesus Nascimento', 'ESCULTURA'),
    ('Luiz Pereira Batista da Silva', 'ESCULTURA'),
    ('Maciel Magalhães Nascimento', 'SERRALHERIA'),
    ('Maele Brito Goes Gomes', 'ESCULTURA'),
    ('Magno Muniz da Silva', 'DESMONTAGEM FORTALEZA'),
    ('Maiara de Souza da Silva Dias', 'ADMINISTRATIVO'),
    ('Maiko de oliveira Silva', 'ESCULTURA'),
    ('Miakon Guilherme Matos Bonfim', 'MARCENARIA'),
    ('Mailson Amorim Soares', 'MARCENARIA'),
    ('Marcelo de Oliveira', 'ADMINISTRATIVO'),
    ('Marcelo de Souza', 'PINTURA'),
    ('Marcelo Fausto da Silva', 'MARCENARIA'),
    ('Marcelo Nascimento de Souza', 'ADMINISTRATIVO'),
    ('Marcelo Ramos de Jesus', 'MARCENARIA'),
    ('Marcio Araujo dos Passos', 'MARCENARIA'),
    ('Marcio Oliveira dos Santos', 'GERAL'),
    ('Marcos Antonio de Jesus', 'GERAL'),
    ('Marcos Antonio de Amorim', 'LAMINAÇÃO'),
    ('Marcos Antunes Pereira', 'SERRALHERIA'),
    ('Marcos Candido da Silva', 'ELÉTRICA'),
    ('Marcos Cesar Silva do Nacimento', 'MARCENARIA'),
    ('Marcos Gonçalves dos Santos Ferreira', 'PINTURA'),
    ('Marcos Henrique Marim Pannia', 'MARCENARIA'),
    ('Marcos Kaique Iafrate da Silva', 'EQUIPE LUIZ'),
    ('Marcos Vinicius Emiliano Alves', 'ESCULTURA'),
    ('Marcus Paulo Oliveira Viana', 'TAPECARIA'),
    ('Marcus Vinicius da Silva Lima', 'ADMINISTRATIVO'),
    ('Maria Lucimar Luima Ferreira', 'ESCULTURA'),
    ('Maria Natalia da Conceicao Silva', 'ADMINISTRATIVO'),
    ('Mariana Basilio Vieira Fernandes Matos', 'GERAL'),
    ('Mariana Batista Pereira', 'PINTURA'),
    ('Mariana do Nascimento Lopes dos Santos', 'GERAL'),
    ('Mariane Bispo Roseno', 'ESCULTURA'),
    ('Mario Alves de Santana', 'PINTURA'),
    ('Mario Eduardo Garcia Benitez', 'MARCENARIA'),
    ('Marlon Nobrega Pfister', 'MARCENARIA'),
    ('Marlon Pereira Silva', 'MARCENARIA'),
    ('Marlon Silva Santana', 'EQUIPE LUIZ'),
    ('Mateus Barbosa Rodrigues da Silva', 'PINTURA'),
    ('Mateus Martins de Carvalho Licar', 'MARCENARIA'),
    ('Mateus da Silva de Almeida', 'SERRALHERIA'),
    ('Mateus Martins da Costa', 'MARCENARIA'),
    ('Matheus Alves dos Santos', 'SERRALHERIA'),
    ('Matheus Aparecido Silva de Araujo', 'PINTURA'),
    ('Matheus Duarte de Sousa', 'MARCENARIA'),
    ('Matheus Goncalves', 'ESCULTURA'),
    ('Matheus Vieira dos Santos', 'MARCENARIA'),
    ('Mauricio da Silva', 'SERRALHERIA'),
    ('Mauricio de Moura', 'SERRALHERIA'),
    ('Mauricio Gomes Silva', 'EQUIPE LUIZ'),
    ('Mauro Jose Ferreira', 'ACABAMENTO'),
    ('Mauro Sergio Dalbem', 'ALMOXARIFADO'),
    ('Maykon Nunes Cruz', 'SERRALHERIA'),
    ('Maykon Silva Santos', 'EQUIPE FELIPE'),
    ('Menandro Rodrigues Filgueira', 'ADMINISTRATIVO'),
    ('Messias Fernandes da Silva', 'EQUIPE FELIPE'),
    ('Michele Ferreira dos Santos', '3D'),
    ('Monique Godoy da Silva Andrade', 'MARKETING'),
    ('Murilo da Silva Claudino', 'ELETRICA'),
    ('Muryllo Conceição da Silva', 'ESCULTURA'),
    ('Nanci do Nascimento Ferreira Luis', 'ADMINISTRATIVO'),
    ('Nataline Gomes de Araujo', 'ESCULTURA'),
    ('Natan Evangelista de Souza', 'ESCULTURA'),
    ('Nayara Lourenço da Silva Santos', 'ESCULTURA'),
    ('Nicolas Pedroza Campeiro Vaz', 'ESCULTURA'),
    ('Nicolas Silva dos Santos', 'ESCULTURA'),
    ('Odair Evaristo ramoni Junior', 'PINTURA'),
    ('Odair Jose Tomaz', 'MARCENARIA'),
    ('Osano Dantas Sá', 'LAMINAÇÃO'),
    ('Oscar Gustavo Garcia Perez', 'MARCENARIA'),
    ('Oscar Gustavo Garcia Perez Junior', 'MARCENARIA'),
    ('Otavio Henrique Carvalho dos Santos', 'ESCULTURA'),
    ('Pablo Cesar Garcia Benitez', 'MARCENARIA'),
    ('Paloma Nascimento Dias', 'ESCULTURA'),
    ('Pasquale Marco Marrone', 'ADMINISTRATIVO'),
    ('Paula da Silva Barbosa', 'ESCULTURA'),
    ('Paulo Djonhes Ribeiro da Silva', 'ESCULTURA'),
    ('Paulo dos Santos Xavier', 'ACABAMENTO'),
    ('Paulo Henrique Soares', 'ADMINISTRATIVO'),
    ('Paulo Marcelo Duarte Brito', 'ALMOXARIFADO'),
    ('Paulo Sergio Barbosa Elias', 'ACABAMENTO'),
    ('Paulo Sergio da Silva', 'ACABAMENTO'),
    ('Paulo Sergio Pereira da Silva', 'ELETRICA'),
    ('Paulo Victor Gomes da Silva', 'PINTURA'),
    ('Pedro Henrique da Silva Souza', 'ESCULTURA'),
    ('Pedro Tabolassi da Silva', 'ESCULTURA'),
    ('Rafael da Silva Tonini', 'MARCENARIA'),
    ('Rafael da Silva Nunes de Jesus', 'PINTURA'),
    ('Rafael Ferreira da Silva', 'LAMINAÇÃO'),
    ('Rafael Peroco', 'PINTURA'),
    ('Rafael Warzee dos Santos', 'ADMINISTRATIVO'),
    ('Raphael Abreu Magalhaes', 'MARCENARIA'),
    ('Raphael Teixeira dos Santos', 'ADMINISTRATIVO'),
    ('Raquel Aparecida da Silva', 'RH'),
    ('Raquel Shirles Gomes de Sá', 'ESCULTURA'),
    ('Reginaldo Jesus dos Santos', 'LAMINAÇÃO'),
    ('Reinaldo Almeida Prudente', 'MARCENARIA'),
    ('Reinaldo Braga Tavares', 'SERRALHERIA'),
    ('Renan Vieira Martins de Gregorio', 'ESCULTURA'),
    ('Renata Figueredo Rodrigues', 'ADEREÇO'),
    ('Renato de Aquino Ribeiro', 'MARCENARIA'),
    ('Renato Sena dos Santos junior', 'SERRALHERIA'),
    ('Renato Sousa da Silva', 'DESMONTAGEM FORTALEZA'),
    ('Ricardo Alexandre Miguel', 'MARCENARIA'),
    ('Ricardo Nascimento Portela', 'SERRALHERIA'),
    ('Ricardo Prado  Magalhães', 'ESCULTURA'),
    ('Roberto Anderson Moura', 'MARCENARIA'),
    ('Roberto Jose Sarmiento Carrillo', 'SERRALHERIA'),
    ('Roberto Leandro Martins Pereira', 'PINTURA'),
    ('Robertson dos Santos Rocha', 'MARCENARIA'),
    ('Robson Carlos Santos', 'MARCENARIA'),
    ('Robson Lopes da Silva', 'ESCULTURA'),
    ('Robson Mendes Oliveira Morais', 'PINTURA'),
    ('Rocelio Francisco de Melo', 'MARCENARIA'),
    ('Rochenildo Jose da Silva', 'MARCENARIA'),
    ('Rodolfo da Silva Nunes', 'SERRALHERIA'),
    ('Rodrigo Alex Tavares Ignacio', 'PINTURA'),
    ('Rodrigo Alves', 'SERRALHERIA'),
    ('Rodrigo de Jesus Gonçalves de Souza', 'ESCULTURA'),
    ('Rodrigo Estevao de Lima', 'PINTURA'),
    ('Rodrigo Nascimento de Souza', 'MARCENARIA'),
    ('Rogerio Henrique Martins da Cunha', 'PINTURA'),
    ('Romulo Benedito Cavalcante Teixeira', 'PINTURA'),
    ('Ronaldo Aparecido de Souza', 'MARCENARIA'),
    ('Roosevelt Nery de Campos', 'ACABAMENTO'),
    ('Samuel Magalhaes', 'ESCULTURA'),
    ('Sandra Regina Varano', 'ESCULTURA'),
    ('Sandro Mendes Silva', 'PINTURA'),
    ('Sergio Alejandro Facchinett Maluf', 'SERRALHERIA'),
    ('Sergio Oliveira Santos', 'GERAL'),
    ('Siloel Antonio do Nascimento', 'ACABAMENTO'),
    ('Simone Ferreira Bueno', 'ESCULTURA'),
    ('Stefany Silva Soares', 'ESCULTURA'),
    ('Sthefany Barbosa Queiroz', 'ESCULTURA'),
    ('Talyson Lourenco Oliveira da Silva', 'MARCENARIA'),
    ('Tamires Alves dos Santos', 'ADMINISTRATIVO'),
    ('Taynan Modesto Rodrigues da Silva', 'ADMINISTRATIVO'),
    ('Thamiris dos Santos Diniz', 'ESCULTURA'),
    ('Thaynara Christine Araujo Pereira', 'PINTURA'),
    ('Thayrone Lima D Assumpção', 'ADMINISTRATIVO'),
    ('Thiago Gabriel da Silva', 'ESCULTURA'),
    ('Thiago Henrique Varano Evangelista', 'ACABAMENTO'),
    ('Thiago Mantovani de Oliveira Ramos', 'MARCENARIA'),
    ('Thiago da Silva Monteiro', 'MARCENARIA'),
    ('Thiago Teixeira da Silva', '3D'),
    ('Tiago Rocha da Silva', 'ESCULTURA'),
    ('Tiago Ribeiro dos Santos', 'ACABAMENTO'),
    ('Tomas Di Febbo', 'ROUTER'),
    ('Tony Kifua Lin', 'ADMINISTRATIVO'),
    ('Valdson Vagno Silva dos Santos', 'MARCENARIA'),
    ('Vandemarcos Marques da Silva', 'ACABAMENTO'),
    ('Vanderlei Batista Pereira', 'MARCENARIA'),
    ('Victor Henrique Tecco', '3D'),
    ('Victor Lino da Silva', 'MARCENARIA'),
    ('Victor Silvestre da Silva', 'ESCULTURA'),
    ('Victorio Augusto Duarte de Sousa', 'MARCENARIA'),
    ('Vinicius dos Santos Chaves', 'SERRALHERIA'),
    ('Vinicius Franco de Souza', 'ESCULTURA'),
    ('Vinicius Gabriel Ferreira de Souza', 'ESCULTURA'),
    ('Vitor Nunes Silva', 'PINTURA'),
    ('Vitoria Nascimento Dias', 'ESCULTURA'),
    ('Wagner Rodrigues Cacimiro', 'MARCENARIA'),
    ('Wanderson Reis Souza', 'ADMINISTRATIVO'),
    ('Welker de Jesus Paim', 'MARCENARIA'),
    ('Wellington Carlos de Souza Evangelista', 'PINTURA'),
    ('Wellington Vieira de Souza', 'MARCENARIA'),
    ('Welton dos Santos Fonseca', 'PINTURA'),
    ('Weslei Vicente Ferreira Fernandes de Souza', 'SERRALHERIA'),
    ('Weslwy Gonçalves Guedes', 'ESCULTURA'),
    ('Weslley Gonçalves dos Santos', 'MARCENARIA'),
    ('Weverton Vitor Oliveira da Cruz', 'ESCULTURA'),
    ('Wilkerson Alves dos Santos Costa', 'MARCENARIA'),
    ('Willian Honorio Pereira de Sousa', 'SERRALHERIA'),
    ('Wladimir Antonio Garcia', 'MARCENARIA'),
    ('Yasmin de Souza Andrade', 'ADMINISTRATIVO'),
    ('Yuri Henrique Soares de Souza', 'SERRALHERIA'),
    ('Fabio Paulino dos Santos', 'PINTURA')
) AS v(name, dept)
WHERE p.name = v.name;
